### PR TITLE
DEC-265: Title -> Name

### PR DESCRIPTION
**Pull request by jgondron**
Changed all title properties to names for all objects to correspond with the API changes in honeycomb. This must be merged with https://github.com/ndlib/honeycomb/pull/110

### CODE REVIEW

**Comment by danthewolfe** [comment]
Tested locally. Appears to work after clearing cache out.

:+1:

**Comment by danthewolfe** [comment]
Need to discuss changing "title" in css styles to "name". @jonhartzler @jaronkk

**Comment by jaronkk** [comment]
I'm okay with leaving the class names as they currently are.

**Comment by jaronkk** [comment]
:+1:

**Pull request merged**
