### PR TITLE
fix the title not showing if there is no background image.

### PR DESCRIPTION
**Pull request by jonhartzler**

### CODE REVIEW

**Comment by jaronkk** [comment]
The issue here was that the title doesn't display if there is *no* image for the collection.

**Comment by jaronkk** [comment]
digital_exhibits_and_collections

**Comment by jonhartzler** [comment]
that is what i tried to fix
screen shot 2015-09-09 at 1 50 37 pm

**Comment by jaronkk** [comment]
Ignore my comments, I did not have actually have the changes pulled down.

**Comment by jaronkk** [comment]
No way to address the hound issues without some underlying CSS changes.

**Comment by jaronkk** [comment]
:+1:

**Comment by danthewolfe** [comment]
:+1:

**Pull request merged**
