### PR TITLE
DEC-1061: Users would like a way to embed beehive pages

### PR DESCRIPTION
**Pull request by jgondron**
-Fixed a bug with compact param not being preserved on pagination links
-Fixed a height calculation problem when compact=false

### CODE REVIEW

**Comment by jonhartzler** [comment]
👍

**Comment by rfox2** [comment]
👍

**Comment by danthewolfe** [comment]
👍

**Comment by jgondron** [comment]
👍

**Comment by danthewolfe** [comment]
👎

**Pull request merged**
