### PR TITLE
Mobile fixes

### PR DESCRIPTION
**Pull request by awetherill**
Fixed green labeled issues from the QA spreadsheet: https://docs.google.com/a/nd.edu/spreadsheets/d/1Vxr-PXJoYjZZtYuwA82VBtKbUeOan4I7p9jjZD7P7MU/edit?usp=sharing

### CODE REVIEW

**Comment by jaronkk** [comment]
@awetherill Can you address the hound issues that are complaining about the properties order?

**Comment by danthewolfe** [comment]
:+1:

**Comment by jgondron** [comment]
:+1:

**Comment by jaronkk** [comment]
:+1:

**Pull request merged**
