### PR TITLE
Create thumbnail image for the "more" hover scroll down thingy.

### PR DESCRIPTION
**Pull request by danthewolfe**
Create a scroll down thingy that looks pretty and gives an idea of what you're scrolling to the bottom of the page for.

### CODE REVIEW

**Comment by jgondron** [comment]
:+1:

**Comment by jaronkk** [comment]
I got a warning: "Warning: Unknown DOM property class. Did you mean className?"

**Comment by jaronkk** [comment]
:+1:

**Comment by jonhartzler** [comment]
I like this.  My one comment is I think I would like to see clicking the down arrow take you down and clicking the showcase take you to the showcase.

**Pull request merged**
