### PR TITLE
DEC-391 Fix header on vertically scrolling pages

### PR DESCRIPTION
**Pull request by danthewolfe**
Problem: When pages were scrolled vertically, the absolutely positioned modals didn't look right.

Fix: Basically made the header fixed on all vertically scrolling pages. This involved a little moving things around and additional CSS changes so as not to break existing presentation in other places.

### CODE REVIEW

**Comment by jaronkk** [comment]
How does this end up looking on a phone?  I'd be worried about the fixed header taking up too much real estate

**Comment by danthewolfe** [comment]
it looks a bit large, in my opinion, but it does not change current behavior.

**Comment by jaronkk** [comment]
:+1:

**Comment by jgondron** [comment]
:+1:

**Pull request merged**
