### PR TITLE
DEC-545 added small tag to 2nd headline for when it's visible on the …

### PR DESCRIPTION
**Pull request by awetherill**
…Collection cover page.

### CODE REVIEW

**Comment by jonhartzler** [comment]
I think this would be a little better if it followed the showcase page and only had the underlines the same length as the text plus a little.

**Comment by jonhartzler** [comment]
:+1:   I am thinking of moving the comment I have to its own ticket

**Comment by danthewolfe** [comment]
Can we fix hound errors, then :+1:

**Comment by jonhartzler** [comment]
we can but i am usually a little hesitant to fix the line depth one:  
Selector should have depth of applicability no greater than 2, but was 4

**Comment by danthewolfe** [comment]
I mean the spacing and order-related ones. I have learned to completely ignore Hound's comments on selector depth.

**Pull request merged**
